# Generated by Django 3.2 on 2025-10-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'Paid'), (-10, 'Not Paid')], default=-10),
        ),
    ]
