# Generated by Django 3.2 on 2025-08-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
