# Generated by Django 3.2 on 2025-09-30 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='media',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products/'),
            preserve_default=False,
        ),
    ]
