# Generated by Django 3.2 on 2025-10-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20250930_1812'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketLines',
            new_name='BasketLine',
        ),
    ]
