# Generated by Django 3.2 on 2025-10-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20250930_1812'),
        ('basket', '0002_rename_basketlines_basketline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketline',
            unique_together={('basket', 'product')},
        ),
    ]
